name: CI/CD Xamarin

on: push

jobs:
  Build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
        
      - name: Setup Android Signing
        run: (echo ${{ secrets.KEYSTORE }} | base64 — decode) > Netflix.Android/Netflix.jks
        
      - name: Set Android Version
        uses: damienaicheh/update-android-version-manifest-action@v1.0.0
        with:
          android-manifest-path: Netflix.Android/Properties/AndroidManifest.xml
          version-name: 1.0
          version-code: ${{ github.run_number }}
          print-file: true
        
      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Build Android
        run: MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=Netflix /p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }} /p:AndroidSigningKeyStore=Netflix.jks /p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} Netflix.Android/Netflix.Android.csproj
        
      - name: Setuo App Center CLI
        run: npm install -g appcenter-cli
        
      - name: Upload Android app to App Center
        run: appcenter distribute release --silent --file Netflix.Android/bin/Release/com.echolumaque.NetflixForms.apk --app EchoLumaque/Netflix --group Collaborators --token ${{ secrets.APP_CENTER_TOKEN }}
