name: CI on Push and Pull Request

on: [push]

jobs:
  #Practice:
    #runs-on: macos-latest
    #steps:
    #- uses: actions/checkout@v1
    #- name: Run a one-line script
      #run: echo Hello, world!
    #- name: Run a multi-line script
      #run: |
        #echo Add other actions to build,
        #echo test, and deploy your project.
    #- name: Show what's in the directory
      #run: |
        #ls
    #- name: Show what all is in the parent directory
      #run: |
        #cd ..
        #ls
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Android
      run: |
        nuget restore
        msbuild Netflix.Android/Netflix.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
    - uses: actions/upload-artifact@v2.2.4
    - name: Upload artifact
      with:
        name: Netflix.Forms
        path: Netflix/Netflix.Android/bin/Release/com.echolumaque.Netflix.Forms.apk
        
  AppCenter:
    runs-on: ubuntu-latest
    steps:
      - uses: wzieba/AppCenter-Github-Action@v1.3.2
      - name: Publish artifact to App Center
        with: 
          appName: Netlflix.Forms
          token: a2f394562c314c4c5d08a7c7d5dc845fa0de64c8
          group: Collaboratos;Testers
          file: Netflix/Netflix.Android/bin/Release/com.echolumaque.Netflix.Forms.apk
          debug: false
  #iOS:
    #runs-on: macos-latest
    #steps:
    #- uses: actions/checkout@v1
    #- name: iOS
      #run: |
        #nuget restore
        #msbuild Netflix.iOS/Netflix.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Release
